// <auto-generated />
using ABCDMall.Modules.Users.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ABCDMall.Modules.Users.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MallDbContext))]
    [Migration("20260420052000_AddIsActiveToUsers")]
    partial class AddIsActiveToUsers
    {
    }
}
